version: '3'

services:
  es:
    image: elasticsearch-position-similarity:${ES_VERSION}
    container_name: es
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        - ES_VERSION
    environment:
      - node.name=es
      - cluster.name=es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - mem_limit=2048m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
